version: '3'

services:
  pgdb:
    container_name: pg_db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdb-volume:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - '3001:8081'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pgdb:5432/postgres?sslmode=disable
    depends_on:
      - pgdb

volumes:
  pgdb-volume:
